osx_image: xcode11
language: swift
xcode_project: CountryPicker/CountryPicker.xcodeproj
script:
  - xcodebuild clean build test -enableCodeCoverage YES -project CountryPicker/CountryPicker.xcodeproj -scheme CountryPicker -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 8' ONLY_ACTIVE_ARCH=YES
after_success:
  - bash <(curl -s https://codecov.io/bash
